### ISSUE TITLE
Save_Anywhere: Jump to last saved time & position after wake up from sleep

### ISSUE THREAD

**Issue by hcoona** [janavarro95/Stardew_Valley_Mods#12]
Reproduce steps:
1. Press "K" on day n somewhere
2. Go to bed for a sleep
3. Move after wake up

Expected:
Starting a new day around your bed

Actual:
Bring back to the last saved time & position

**Comment by hcoona** [comment]
I would suggest clear the saved player data after go to bed for normal saving

**Comment by Pathoschild** [comment]
Fixed in #22.
