### ISSUE TITLE
Save Anywhere: error if you save in the shed and try to load

### ISSUE THREAD

**Issue by Pathoschild** [janavarro95/Stardew_Valley_Mods#23]
If you save in a shed, you get this error when loading:
> ![](https://user-images.githubusercontent.com/230581/29102597-4e870b22-7c88-11e7-841e-24beea9de1c1.png)

See attached save data: [HeatVamp_135366865.json](https://github.com/janavarro95/Stardew_Valley_Mods/files/1210125/HeatVamp_135366865.json.txt).

**Comment by janavarro95** [comment]
Going to look into this today. My best hunch is the glitch relates to a multitude of sheds being able to exist at one time so the game doesn't know which one to warp the character to.

**Comment by janavarro95** [comment]
Fixed in newest update. Added in a line of code in SaveManager.cs to try and grab the unique name of the map which is used for farm buildings. If there is no unique name set for that map it will grab the default name of the map such as FarmHouse or Farm.
