### ISSUE TITLE
Not savind new Quest instance

### ISSUE THREAD

**Issue by gbartholomeu** [janavarro95/Stardew_Valley_Mods#26]
Description: Once you pick a quest, saves the game, quits the game and load the save again, the user will have the selected quest and the same quest will be available for picking again.

I did a test and picked the same quest five times.

How to: Pick a quest, save the game, quit, load. The quest will be available again.

Here are the game screenshots:
[IssuePrints.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/1609151/IssuePrints.zip)

**Comment by janavarro95** [comment]
Seems like an issue with Stardew Valley and not this mod. Weird. Not sure I will fix this on my end as I am using the game's internal saving. Also it is embarrassing that an issue was left open for a year without me addressing it, so my apologies.
