### ISSUE TITLE
CustomShopMod_Redux_GUI

### ISSUE THREAD

**Issue by LeetCodes** [janavarro95/Stardew_Valley_Mods#4]
hi, in the file Custom_Shop_Redux_Config.txt it says this 'Key binding for saving anywhere. Press this key to save anywhere!'

i dont understand? saving what anywhere?

**Comment by janavarro95** [comment]
Well that was definitely a typo, and I'm currently not supporting that mod anymore, so I don't think this is an issue anymore. Maybe in the future I'll bring it back again.

**Comment by LeetCodes** [comment]
no problem, i was mainly looking at the source to learn and just wanted to report, thanks, have a nice day :)
