### ISSUE TITLE
Sleeping between 2:00 AM and 5:50 AM miscalculates time till 6:00 AM

### ISSUE THREAD

**Issue by perkinslr** [janavarro95/Stardew_Valley_Mods#41]
So, at 1:50 AM late (2550), the clock gets set to 1:50 AM early (150).  If you then sleep, the time till 6:00 AM is calculated as 3000-150, or 2850, which then makes the artisan goods process faster and counts as a full night's sleep for the player (full stamina bar in the morning).  

I'm not sure what the proper solution is, maybe detect when they got to bed and adjust the clock, or maybe replace the time-till-6 calculation via Harmony with a proper modulo check.

**Comment by janavarro95** [comment]
Fixed in most recent version of Development branch. Release version coming within a week.
