### ISSUE TITLE
Broken in Stardew Valley 1.3.29

### ISSUE THREAD

**Issue by Nekuake** [janavarro95/Stardew_Valley_Mods#42]

**Comment by janavarro95** [comment]
Not sure what is broken here. Any mod in particular?

**Comment by rmenessec** [comment]
This probably relates to the post-1.3.28 changes that have broken quite a lot of mods. Some mods may only require a recompile against SMAPI 2.8-beta, and some may require more extensive changes.

**Comment by janavarro95** [comment]
All mods are checked to be compatible with 1.3.32 in the Development branch now. Update to Nexus coming in a few days.
