### ISSUE TITLE
Stardew Symphony: Support for compressed formats?

### ISSUE THREAD

**Issue by rmenessec** [janavarro95/Stardew_Valley_Mods#43]
Would you consider adding support for at least one compressed music format? The one music pack I've seen contains only 5 songs, but is over 200MiB.

If adding support for the common formats (FLAC, Ogg Vorbis, MP3, _etc._) is too much effort, please consider adding support for [Opus](https://opus-codec.org/). The codec is capable of both lossy and lossless compression; has variable bit rates ranging from a few Kbps for VoIP to 24-bit multichannel master-grade; is fully cross-platform; and is supported by every modern web browser.

Thanks in advance.

**Comment by janavarro95** [comment]
Unfortunately I am limited by XNA's ability to load in only .wav files. I'm unsure there is much else I could do on my end without having to include an external library or writing my own loaders for common formats which is lower on the priority sheet for the moment. Will definitely consider this in the future.

**Comment by janavarro95** [comment]
Actual scratch the above. I looked into a free library (NAudio: https://github.com/naudio/NAudio) that allows for this kind of support. Added in mp3 file support so far. Maybe will add more in the future.
