### ISSUE TITLE
Italian translation for 'Happy Birthday'

### ISSUE THREAD

**Issue by MakinDay** [janavarro95/Stardew_Valley_Mods#57]
[Italian.zip](https://github.com/janavarro95/Stardew_Valley_Mods/files/3935629/Italian.zip)

**Comment by janavarro95** [comment]
Unfortunately since the mod went a rewrite this year and added a ton more dialogue, it would be best to release a content pack version for the Italian version as well. Not sure this will reach you at this point, but since I'm cleaning these bugs up I thought it would be good to do so.
