### ISSUE TITLE
Save_Anywhere not working (Not compatible with the lastest version of the game)

### ISSUE THREAD

**Issue by Dovahkao** [janavarro95/Stardew_Valley_Mods#7]
Hi! I found your mods on NexusMod and i realize you could save my life. I bought the game but i can't play because it crashes at random moments. So with the save anywhere i can save everytime and if it crashes, its ok, i dont have to start the day again. However when i try to execute the mod i get that error message 
![error](https://cloud.githubusercontent.com/assets/28583660/25880598/c66d626a-350e-11e7-8d9f-e317705c2a21.png). What should i do? Can you help me? Pleeease T_T

**Comment by janavarro95** [comment]
Hey!

Yea the mod is really outdated at the moment, and it will be some time
before I get a chance to fix it since life is really busy right now.

Hang tight for a bit please!

Thanks and sorry!

Josh N.

**Comment by Dovahkao** [comment]
Thanks! I'll be waiting ^^ I'm so happy that i found your mods haha

**Comment by janavarro95** [comment]
Hey, I just updated all of my mods to SMAPI 1.12 and SDV 1.2 so I think this should be good now!
