### ISSUE TITLE
there are no files of past versions of STARDUST mod on Nexus Mods

### ISSUE THREAD

**Issue by V-I-L** [janavarro95/Stardew_Valley_Mods#77]
WHERE IS THE STARDUST CORE OLD VERSION FOR STARDEW VALLEY 145.151???????
WHY ARE THERE NO PREVIOUS VERSIONS ON NEXUS MODS?????
I WANT TO PLAY WITH MODS!!!
PLEASE ADD THE OLD VERSIONS OF THIS MOD!!!!

**Comment by janavarro95** [comment]
I can't support older versions of Stardew Valley unfortunately since I do not have a older version of the game to build against. My apologies, had I known this was going to be an issue I would have kept an archival version from longer ago.
