### ISSUE TITLE
Night Owl no longer works

### ISSUE THREAD

**Issue by SwiftyMagee** [janavarro95/Stardew_Valley_Mods#9]
Night Owl needs to be updated for SMAPI 1.14.

**Comment by janavarro95** [comment]
Ahh yes, I do need to update my mods again. I believe SMAPI 1.15 is releasing soon ish, and I shall have my mods updated sometime this next week. Sorry for the delayed response.

**Comment by Pathoschild** [comment]
Fixed by #16 and #17.
